### ISSUE TITLE
`'NoneType' object is not subscriptable` when generating a burndown chart for the new GitHub Projects in an Organization

### ISSUE THREAD

**Issue by filipefigcorreia** [thehale/github-projects-burndown-chart#27]
I am having the following exception when using this application with a private organization:

```
Traceback (most recent call last):
  File "main.py", line 58, in <module>
    project = download_project_data(args)
  File "main.py", line 29, in download_project_data
    project: Project = get_organization_project()
  File "/Code/github-projects-burndown-chart/src/github_projects_burndown_chart/gh/api_wrapper.py", line 32, in get_organization_project
    return Project(project_data)
  File "/Code/github-projects-burndown-chart/src/github_projects_burndown_chart/gh/project.py", line 9, in __init__
    self.name = project_data['name']
TypeError: 'NoneType' object is not subscriptable
```

Any idea on what might be going wrong?

Upon some investigation I discovered that the culprit seems to be this request to the GitHub GraphQL API (organization name redacted):

```
{
   "query":"query OrganizationProject($organization_name: String!, $project_number: Int!, $column_count: Int!, $max_cards_per_column_count: Int!, $labels_per_issue_count: Int!) {\n  organization(login: $organization_name) {\n    project(number: $project_number) {\n      name\n      columns(first: $column_count) {\n        nodes {\n          name\n          cards(first: $max_cards_per_column_count) {\n            nodes {\n              id\n              note\n              state\n              content {\n                ... on Issue {\n                  title\n                  timelineItems(first: 20, itemTypes: [ASSIGNED_EVENT]) {\n                    nodes {\n                      __typename\n                      ... on AssignedEvent {\n                        createdAt\n                      }\n                    }\n                  }\n                  createdAt\n                  closedAt\n                  labels(first: $labels_per_issue_count) {\n                    nodes {\n                      name\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n}",
   "variables":{
      "organization_name":"<my org name>",
      "project_number":1,
      "column_count":5,
      "max_cards_per_column_count":50,
      "labels_per_issue_count":5
   }
}
```

Which is returning the following (request-id redacted):

Headers:
```
{
   "Server":"GitHub.com",
   "Date":"Fri, 11 Nov 2022 10:54:30 GMT",
   "Content-Type":"application/json; charset=utf-8",
   "Transfer-Encoding":"chunked",
   "X-OAuth-Scopes":"admin:org, project, repo",
   "X-Accepted-OAuth-Scopes":"repo",
   "github-authentication-token-expiration":"2023-02-05 10:43:50 UTC",
   "X-GitHub-Media-Type":"github.v4; format=json",
   "X-RateLimit-Limit":"5000",
   "X-RateLimit-Remaining":"4994",
   "X-RateLimit-Reset":"1668167670",
   "X-RateLimit-Used":"6",
   "X-RateLimit-Resource":"graphql",
   "Access-Control-Expose-Headers":"ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset",
   "Access-Control-Allow-Origin":"*",
   "Strict-Transport-Security":"max-age=31536000; includeSubdomains; preload",
   "X-Frame-Options":"deny",
   "X-Content-Type-Options":"nosniff",
   "X-XSS-Protection":"0",
   "Referrer-Policy":"origin-when-cross-origin, strict-origin-when-cross-origin",
   "Content-Security-Policy":"default-src 'none'",
   "Vary":"Accept-Encoding, Accept, X-Requested-With",
   "Content-Encoding":"gzip",
   "X-GitHub-Request-Id":"<some id>"
}
```

Content:
```
b'{"data":{"organization":{"project":null}}}'
```

<a href="https://polar.sh/thehale/github-projects-burndown-chart/issues/27">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/thehale/github-projects-burndown-chart/issues/27/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/thehale/github-projects-burndown-chart/issues/27/pledge.svg">
</picture>
</a>

**Comment by thehale** [comment]
Thanks for the detailed report!

Are you using [**Projects (classic)**](https://docs.github.com/en/issues/planning-and-tracking-with-projects/creating-projects/migrating-from-projects-classic) or the new [GitHub Project boards](https://docs.github.com/en/issues/planning-and-tracking-with-projects/creating-projects/creating-a-project)?

The burndown charts in this repository were designed for **Projects (classic)** and I have not yet tested them with the new GitHub Project boards.

## Proposed Fix

Looking at the [API Documentation](https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/using-the-api-to-manage-projects) for the new project boards, it doesn't seem like it would be too terribly difficult to port this repository to the new version of GitHub projects. Since GitHub is aggressively phasing out **Projects (classic)** I don't see a need to maintain support for them.

The only part of this repository which touches the GitHub API is the [`gh`](https://github.com/thehale/github-projects-burndown-chart/tree/main/src/github_projects_burndown_chart/gh) module (~300 lines), so all updates can be localized there, provided the classes in [`project.py`](https://github.com/thehale/github-projects-burndown-chart/blob/main/src/github_projects_burndown_chart/gh/project.py) retain their current interface.

## Estimated Timeline

Due to current commitments for my master's degree and work, I will not be able to work on updating this repository myself until December 2022 (at the earliest).

That said, even though I haven't yet added a `CONTRIBUTING.md` file to the repo, I am happy to help you (or another interested developer) to create and merge a pull request for this update.

**Comment by filipefigcorreia** [comment]
Ok, I see. I'm using the new GitHub Projects. Unfortunately, I don't expect I would be able to work on this before Jan 2023 either, but I may be able to give it a go after that. 

(PS: Good luck for your master's! And thank you for creating this tool)

**Comment by josalhor** [comment]
I needed a burndown for a project and I hacked together a solution on my branch. Be advised, don't merge this. It is 100% rushed and adhoc for my use case, but it may be useful to you: https://github.com/josalhor/github-projects-burndown-chart

**Comment by thehale** [comment]
@josalhor Glad you got it to work! I'll take a closer look at your approach when I sit down to work on this myself (unless someone else implements it first).
